[main]
# Fuzzel configuration
font=JetBrainsMono Nerd Font:size=12
icon-theme=Papirus
terminal=kitty
width=50
lines=10
horizontal-pad=20
vertical-pad=15
inner-pad=10
image-size-ratio=0.5
line-height=25
letter-spacing=0

[colors]
background=101418ff
text=e1e2e8ff
match=a0cafdff
selection=184975ff
selection-text=d1e4ffff
selection-match=bac8dbff
border=8d9199ff

[border]
width=2
radius=8

[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
cancel=Escape Control+g Control+bracketleft Mod4+d
next=Down Control+j Control+n
prev=Up Control+p 