[main]
# Fuzzel configuration
font=JetBrainsMono Nerd Font:size=12
icon-theme=Papirus
terminal=kitty
width=50
lines=10
horizontal-pad=20
vertical-pad=15
inner-pad=10
image-size-ratio=0.5
line-height=25
letter-spacing=0

[colors]
background=24273aee
text=cad3f5ff
match=a6da95ff
selection=494d64ff
selection-text=ffffff
selection-match=eed49fff
border=33ccffff

[border]
width=2
radius=8

[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
cancel=Escape Control+g Control+bracketleft Super+d
next=Down Control+j Control+n
prev=Up Control+k Control+p 