[main]
# Fuzzel configuration
font=JetBrainsMono Nerd Font:size=12
icon-theme=Papirus
terminal=kitty
width=50
lines=10
horizontal-pad=20
vertical-pad=15
inner-pad=10
image-size-ratio=0.5
line-height=25
letter-spacing=0

[colors]
background=19120cff
text=efe0d5ff
match=fdb876ff
selection=6a3c01ff
selection-text=ffdcbfff
selection-match=e2c0a4ff
border=9e8e81ff

[border]
width=2
radius=8

[dmenu]
exit-immediately-if-empty=yes

[key-bindings]
cancel=Escape Control+g Control+bracketleft Mod4+d
next=Down Control+j Control+n
prev=Up Control+p 