preload = $HOME/dotfiles/assets/wallpapers/evilpuccin.png
wallpaper = DP-3,$HOME/dotfiles/assets/wallpapers/evilpuccin.png
wallpaper = DP-1,$HOME/dotfiles/assets/wallpapers/evilpuccin.png
wallpaper = HDMI-A-1,$HOME/dotfiles/assets/wallpapers/evilpuccin.png
splash = false
