#!/usr/bin/env fish

# Launch wallpaper picker in floating mode centered
kitty --class floating-wallpaper \
      --override window_padding_width=10 \
      --override remember_window_size=no \
      --override initial_window_width=120c \
      --override initial_window_height=40c \
      --override placement_strategy=center \
      -e python3 /home/martin/Documents/applaunch/wallpaper_picker.py