#!/usr/bin/env fish

# Launch app launcher in floating mode centered
kitty --class floating-apps \
      --override window_padding_width=10 \
      --override remember_window_size=no \
      --override initial_window_width=80c \
      --override initial_window_height=40c \
      --override placement_strategy=center \
      -e python3 /home/martin/Documents/applaunch/app_launcher.py