# Matugen Configuration
# Material Design 3 color generation from wallpapers

[config]
# Global settings
scheme = "material"
mode = "dark"
contrast = "standard"

# Template definitions
[templates.hyprland]
input_path = "~/dotfiles/matugen/templates/hyprland.template"
output_path = "~/dotfiles/hypr/conf/colors.conf"

[templates.waybar]
input_path = "~/dotfiles/matugen/templates/waybar.template"
output_path = "~/dotfiles/waybar/colors.css"

[templates.waybar-config]
input_path = "~/dotfiles/matugen/templates/waybar-config.template"
output_path = "~/dotfiles/waybar/config"

[templates.fuzzel]
input_path = "~/dotfiles/matugen/templates/fuzzel.template"
output_path = "~/dotfiles/fuzzel/fuzzel.ini"

[templates.dunst]
input_path = "~/dotfiles/matugen/templates/dunst.template"
output_path = "~/dotfiles/dunst/dunstrc"

[templates.kitty]
input_path = "~/dotfiles/matugen/templates/kitty.template"
output_path = "~/dotfiles/kitty/theme-dynamic.conf"

# GTK theming templates
[templates.gtk3]
input_path = "~/dotfiles/matugen/templates/gtk3.template"
output_path = "~/dotfiles/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "~/dotfiles/matugen/templates/gtk4.template"
output_path = "~/dotfiles/gtk-4.0/colors.css"

# Bottom Waybar templates
[templates.waybar-bottom-config]
input_path = "~/dotfiles/matugen/templates/waybar-bottom-config.template"
output_path = "~/dotfiles/waybar/config-bottom"

[templates.waybar-bottom-style]
input_path = "~/dotfiles/matugen/templates/waybar-bottom-style.template"
output_path = "~/dotfiles/waybar/style-bottom.css"

# QuickShell theming
[templates.quickshell]
input_path = "~/dotfiles/matugen/templates/quickshell.template"
output_path = "~/.local/state/quickshell/user/generated/colors.json"

