preload = /home/martin/dotfiles/assets/wallpapers/evilpuccin.png
wallpaper = DP-3,/home/martin/dotfiles/assets/wallpapers/evilpuccin.png
wallpaper = DP-1,/home/martin/dotfiles/assets/wallpapers/evilpuccin.png
wallpaper = HDMI-A-1,/home/martin/dotfiles/assets/wallpapers/evilpuccin.png
splash = false
