# Useful aliases for dotfiles system
# Generated by modular installer

function ll
    ls -la $argv
end

function la
    ls -A $argv
end

function l
    ls -CF $argv
end

function ..
    cd ..
end

function ...
    cd ../..
end

function grep
    command grep --color=auto $argv
end

function df
    command df -h $argv
end

function free
    command free -h $argv
end

function ps
    command ps aux $argv
end

# Git aliases
function g
    git $argv
end

function gs
    git status $argv
end

function ga
    git add $argv
end

function gc
    git commit $argv
end

function gp
    git push $argv
end

function gl
    git log --oneline $argv
end

# System management
function sysinfo
    system-monitor all
end

function logs
    journalctl -f $argv
end

function ports
    netstat -tuln $argv
end

# Development shortcuts
function mkcd
    mkdir -p $argv[1]; and cd $argv[1]
end

function extract
    if test -f $argv[1]
        switch $argv[1]
            case '*.tar.bz2'
                tar xjf $argv[1]
            case '*.tar.gz'
                tar xzf $argv[1]
            case '*.bz2'
                bunzip2 $argv[1]
            case '*.rar'
                unrar x $argv[1]
            case '*.gz'
                gunzip $argv[1]
            case '*.tar'
                tar xf $argv[1]
            case '*.tbz2'
                tar xjf $argv[1]
            case '*.tgz'
                tar xzf $argv[1]
            case '*.zip'
                unzip $argv[1]
            case '*.Z'
                uncompress $argv[1]
            case '*.7z'
                7z x $argv[1]
            case '*'
                echo "'$argv[1]' cannot be extracted via extract()"
        end
    else
        echo "'$argv[1]' is not a valid file"
    end
end
