function update_fish_colors --description 'Update fish colors to match current theme'
    # This function is called by the dynamic theme switcher
    # Colors are generated by matugen from wallpaper
    
    # Check if dynamic theme file exists
    if test -f ~/dotfiles/fish/theme-dynamic.fish
        source ~/dotfiles/fish/theme-dynamic.fish
        echo "🌌 Fish colors updated to match Evil Space dynamic theme"
    else
        echo "⚠️  Dynamic theme file not found. Run: matugen color $(cat ~/.cache/swww/eDP-1)"
        # Fallback to default Evil Space colors
        source ~/dotfiles/fish/functions/update_fish_colors_fallback.fish
    end
end

function update_fish_colors_fallback --description 'Fallback Evil Space colors'
    # Default Evil Space theme colors (fallback)
    set -U fish_color_autosuggestion brblack
    set -U fish_color_cancel -r
    set -U fish_color_command brblue
    set -U fish_color_comment brblack
    set -U fish_color_cwd green
    set -U fish_color_cwd_root red
    set -U fish_color_end brgreen
    set -U fish_color_error brred
    set -U fish_color_escape brcyan
    set -U fish_color_history_current --bold
    set -U fish_color_host normal
    set -U fish_color_host_remote yellow
    set -U fish_color_normal normal
    set -U fish_color_operator brcyan
    set -U fish_color_param cyan
    set -U fish_color_quote yellow
    set -U fish_color_redirection cyan --bold
    set -U fish_color_search_match bryellow --background=brblack
    set -U fish_color_selection white --bold --background=brblack
    set -U fish_color_status red
    set -U fish_color_user brgreen
    set -U fish_color_valid_path --underline
    
    # Pager colors
    set -U fish_pager_color_completion normal
    set -U fish_pager_color_description B3A06D yellow -i
    set -U fish_pager_color_prefix normal --bold --underline
    set -U fish_pager_color_progress brwhite --background=cyan
    set -U fish_pager_color_selected_background -r
end 