# General Configuration
# Managed by Rice Studio

general {
    # Border Settings
    border_size = 2
    
    # Gap Settings  
    gaps_in = 3
    gaps_out = 10
    gaps_workspaces = 50
    
    # Border Interaction
    resize_on_border = false
    extend_border_grab_area = 0
    hover_icon_on_border = false
}
